# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-25 17:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import jsonfield.fields
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetadataSchema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=120)),
                ('version', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('schema', jsonfield.fields.JSONField()),
            ],
            options={
                'ordering': ('name', '-version'),
            },
        ),
        migrations.AlterUniqueTogether(
            name='metadataschema',
            unique_together=set([('name', 'version')]),
        ),
    ]
