# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-25 17:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata_organizer', '0003_metadataschema_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metadataschema',
            old_name='active',
            new_name='published',
        ),
    ]
