# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-25 18:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata_organizer', '0004_auto_20160425_1759'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metadataschema',
            options={'ordering': ('title', '-version')},
        ),
        migrations.RenameField(
            model_name='metadataschema',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterUniqueTogether(
            name='metadataschema',
            unique_together=set([('title', 'version')]),
        ),
    ]
