# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-27 14:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('metadata_organizer', '0005_auto_20160425_1854'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('datafile_id', models.IntegerField(default=1)),
                ('metadata', jsonfield.fields.JSONField()),
                ('published', models.BooleanField(default=True)),
                ('version', models.IntegerField(default=1, help_text='Placeholder')),
            ],
            options={
                'ordering': ('schema', '-version'),
            },
        ),
        migrations.AlterField(
            model_name='metadataschema',
            name='published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='filemetadata',
            name='schema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metadata_organizer.MetadataSchema'),
        ),
        migrations.AlterUniqueTogether(
            name='filemetadata',
            unique_together=set([('schema', 'datafile_id', 'version')]),
        ),
    ]
